#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X
# pgrep bspswallow || bspswallow &

# bspc config border_width         2
# bspc config window_gap           6

bspc config top_padding 22
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 0
bspc config single_monocle        true

bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc ignore_ewmh_fullscreen      "all"

# bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#8FBCBB"
# bspc config focused_border_color "#61AFEF"
# bspc config focused_border_color "#005577"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
